-- ???????
SELECT ID, VER_ID, CODE, NAME, VER_TYPE, REBUILD, CCODE, CSEASON, MAXGC
FROM CV;

SELECT ID, MLINK, MTYPE, NAME, TSD, WIND, WIND2, CV_ID, USE
FROM CVMETEO;

-- ??????????? ???????
SELECT ID, CV_ID, START_DT, STOP_DT, CALC, CALCNAME, RES, REM, SEASON, ROOT_CVRUN_ID, T, V, D, L
FROM CVRUN
ORDER BY START_DT ;

SELECT cv.NAME, cnt.*, IST.* 	-- sele?t count(*)
FROM ISTCNT ic 
inner JOIN CNT cnt ON cnt.ID = ic.CNT_ID 
LEFT JOIN CV cv ON cv.ID = ic.CV_ID 
LEFT JOIN IST ON IST.ID = cnt.IST_ID 
WHERE CV_ID = 32;

-- ???????? ?????? ????????
SELECT * FROM IST;

-- ????? ???????? ? ?????????
SELECT * FROM ISTCNT;
SELECT * FROM CNT;

-- ???????? ? ???????
SELECT * FROM POLCNT WHERE CV_ID = 32;

-- ???????? ? ???????
SELECT * FROM USE WHERE CV_ID = 32;

-- ?????? ?????????? ???????? ? ???????
SELECT * FROM RASPLO WHERE CV_ID = 32;

-- ????????? ????? ? ???????
SELECT * FROM RASPOINT WHERE CV_ID = 32;



SELECT cv.NAME, cnt.*, IST.* 	-- sele?t count(*)
FROM ISTCNT ic 
inner JOIN CNT cnt ON cnt.ID = ic.CNT_ID 
LEFT JOIN CV cv ON cv.ID = ic.CV_ID 
LEFT JOIN IST ON IST.ID = cnt.IST_ID 
WHERE CV_ID = 32;



SELECT * FROM USE WHERE CV_ID = 32;
SELECT * FROM MTACT WHERE CV_ID = 32;
SELECT * FROM PFON WHERE CV_ID = 32;
SELECT * FROM POLCNT WHERE CV_ID = 32;
SELECT * FROM RASPLO WHERE CV_ID = 32;
SELECT * FROM RASPOINT WHERE CV_ID = 32;
SELECT * FROM SHARE WHERE CV_ID = 32;

SELECT * -- SELECT COUNT(*)
FROM RESDATA
JOIN RESTYPE ON RESTYPE.ID = RESDATA.RESTYPE_ID 
JOIN RASPOINT ON RASPOINT.ID = RESDATA.RASPOINT_ID  
JOIN RESCODE ON RESCODE.ID = RESTYPE.RESCODE_ID
JOIN RESSHARE ON RESSHARE.RESDATA_ID = RESDATA.ID 
JOIN SRES ON SRES.RESSHARE_ID = RESSHARE.ID 
WHERE RESCODE.CVRUN_ID = 134 
;        

SELECT * -- SELECT COUNT(*)
FROM RESDATA
LEFT JOIN RESTYPE ON RESTYPE.ID = RESDATA.RESTYPE_ID 
LEFT JOIN RASPOINT ON RASPOINT.ID = RESDATA.RASPOINT_ID  
LEFT JOIN RASPLO ON RASPLO.ID = RESDATA.RASPLO_ID 
LEFT JOIN RESCODE ON RESCODE.ID = RESTYPE.RESCODE_ID
WHERE RASPOINT_ID IS NOT NULL;


SELECT * 
FROM RESTYPE
JOIN RESCODE ON RESCODE.ID = RESTYPE.RESCODE_ID 
WHERE RESCODE.CVRUN_ID = 161
;   
SELECT * FROM RESCODE
SELECT * FROM RESTYPE;
SELECT * FROM RESCODE r ;
SELECT * FROM RASPOINT r ;
SELECT * FROM SHARE;
SELECT * FROM SUBST;


SELECT RESCODE.CODE AS subname, SUBST.NAME, RASPOINT.CODE AS pointname, RESDATA.N_FON, RESDATA.N_C, RASPOINT.NZ_TYPE, IST.IST_NN, SRES.PRC, CECH.NAME AS cechname
FROM RESDATA
JOIN RESTYPE ON RESTYPE.ID = RESDATA.RESTYPE_ID 
JOIN RASPOINT ON RASPOINT.ID = RESDATA.RASPOINT_ID  
JOIN RESCODE ON RESCODE.ID = RESTYPE.RESCODE_ID
JOIN RESSHARE ON RESSHARE.RESDATA_ID = RESDATA.ID 
JOIN SRES ON SRES.RESSHARE_ID = RESSHARE.ID 
JOIN IST ON IST.ID = SRES.IST_ID 
JOIN CECH ON CECH.ID = IST.CH_ID 
JOIN SUBST ON SUBST.CODE = RESCODE.CODE
WHERE RESCODE.CVRUN_ID = 134 
;   

SELECT * FROM CECH;
SELECT * FROM IST i ;
SELECT * FROM RESCODE;
SELECT * FROM CNT;

CNT
